### ISSUE TITLE
error no module named consistency_interface

### ISSUE THREAD

**Issue by auditanimas** [joezuntz/cosmosis#28] opened 2022-06-16 02:39 UTC
HI Joezuntz! I have already tried to install cosmosis in my laptop and got error "no module named consistency_interface" when I tried to run cosmosis planck.ini
 Could you help me to fix this problem?

**Comment by joezuntz** [comment] 2022-06-16 09:51
This implies you are trying to run the demo from the wrong directory. Try going into the `cosmosis-standard-library` directory and running `cosmosis examples/planck.ini`.

The paths in cosmosis files are relative to the directory where you run the program, by default.

Also, do make sure you have done the conda setup commands and the source command described on the installation page, before you start.

**Comment by joezuntz** [comment] 2022-07-04 12:42
Closing since I hope this is fixed above, but do re-open if not.

**Closed by joezuntz** 2022-07-04 12:42 UTC

**Comment by Gabriel-Rodrigues1** [comment] 2023-02-08 22:22
Hi Joe,

I installed Cosmosis because, from what I understand in the documentation, I can perform a survey forecast for massive neutrinos with it.

The problem is that when I try to run "cosmosis examples/planck.ini" inside the cosmosis-standard-library directory I get a "/home/gabriel-r/cosmosis-standard-library/likelihood/planck2018/planck_interface.so: cannot open shared object file: No such file or directory" error.

And when I try to run "cosmosis planck.ini" inside the examples folder, I also get the error of no module named 'consistency_interface'. If you can help me it would be great.

**Comment by joezuntz** [comment] 2023-02-08 22:27
Hi Gabriel.

What did the "make" command print out when you ran it?  It sounds like you may have missed that step.

Cheers,
joe

**Comment by Gabriel-Rodrigues1** [comment] 2023-02-08 22:46
When I ran "cosmosis-build-standard-library" I got some warnings and errors like: 

"src/euclidemu2.cpp:488:62: error: invalid use of incomplete type 'PyFrameObject' {aka 'struct _frame'}
   488 | #define __Pyx_PyFrame_SetLineNumber(frame, lineno) (frame)->f_lineno = (lineno)
       | "

What was printed at the end was: 

 "error: command '/home/gabriel-r/anaconda3/envs/cosmosis/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
make[2]: *** [Makefile:14: ee_install/done] Error 1
make[2]: Leaving directory '/home/gabriel-r/cosmosis-standard-library/structure/EuclidEmulator2'
make[1]: *** [/home/gabriel-r/anaconda3/envs/cosmosis/lib/python3.11/site-packages/cosmosis/config/subdirs.mk:11: all] Error 2
make[1]: Leaving directory '/home/gabriel-r/cosmosis-standard-library/structure'
make: *** [/home/gabriel-r/anaconda3/envs/cosmosis/lib/python3.11/site-packages/cosmosis/config/subdirs.mk:11: all] Error 2
make: Leaving directory '/home/gabriel-r/cosmosis-standard-library' "

**Comment by Gabriel-Rodrigues1** [comment] 2023-02-08 22:58
Despite the errors and warnings, the cosmosis-standard-library directory was generated.

**Comment by joezuntz** [comment] 2023-02-09 11:34
That error means the content of the directory was not compiled correctly, so it will not work.

This seems to be a new python 3.11 problem. Could you try these alternative instructions for me and see if they work?  (I think from the above you're using an existing conda installation - let me know if that's wrong).

```
conda create -n cosmosis-v2 -c conda-forge python=3.10 cosmosis cosmosis-build-standard-library "numpy<1.24"
conda activate cosmosis-v2
source cosmosis-configure
cosmosis-build-standard-library
```

**Comment by Gabriel-Rodrigues1** [comment] 2023-02-09 14:29
Thank you, Joe.

It worked now. I intend to use cosmosis to do a survey forecast using fisher matrix and I have some doubts from what I read in the documentation, so if you don't mind I have a couple of questions:

I saw that there is a Fisher sampler that maybe can be used for this, if it can, can this be done for any galaxy survey?

And where should the Survey specifications go into?

Cheers,
Gabriel

**Comment by joezuntz** [comment] 2023-02-09 15:15
That's great, glad to hear it!

What kind of survey are you thinking about - lensing, clustering, or something else? And are you looking at two-point stats or something else?

What you are describing is generally a two-step process:
- make some mock data, including a covariance (this is where you would include the survey specs)
- run the Fisher sampler on that mock data

Have a look at the two pipelines `examples/lsst_forecast` for an example of doing both of the stages.

Note that Fisher matrices can be quite unreliable and you should carefully check the effect of tuning the parameter step size.

**Comment by Gabriel-Rodrigues1** [comment] 2023-02-09 16:05
Is a clustering and weak lensing survey, its actually the JPAS. Since I am interested in the Impact that the massive neutrinos has especially in the growth of structure, I am looking to the Matter power spectrum. And for what I understand the code can provide the linear and non linear regime, its that correct?

And also, can I choose the Fisher matrix parameters?

**Comment by joezuntz** [comment] 2023-02-09 16:15
I just realised that this discussion is going on an old closed issue, which isn't super useful, so I'll copy them to a new one now and tag you in it to keep things somewhere relevant. I'll answer there.
